export const DELETE_TYPE_SUCCESS = 'DELETE_TYPE_SUCCESS'
export const DELETE_TYPE_ERROR = 'DELETE_TYPE_ERROR'
export const DELETE_TYPE_LOADING = 'DELETE_TYPE_LOADING'
export const CLEAR_STATE = 'CLEAR_STATE'