export const GET_TILE_SUCCESS = 'GET_TILE_SUCCESS'
export const GET_TILE_ERROR = 'GET_TILE_ERROR'
export const GET_TILE_LOADING = 'GET_TILE_LOADING'
export const CLEAR_GET_TILE_STATE = 'CLEAR_GET_TILE_STATE'