export const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS'
export const GET_TYPES_ERROR = 'GET_TYPES_ERROR'
export const GET_TYPES_LOADING = 'GET_TYPES_LOADING'
export const CLEAR_GET_TYPES_STATE = 'CLEAR_GET_TYPES_STATE'