export { default as AdminLogin } from './admin-auth/admin-login'
export { default as AdminLogout } from './admin-auth/admin-logout'
export { default as EditType } from './admin-edit/edit-type/edit-type.container'
export { default as EditTile } from './admin-edit/edit-tile/edit-tile.container'
export { default as AddType } from './admin-add/add-type/add-type.page'
export { default as AddTile } from './admin-add/add-tile/add-tile.page'
export { default as AdminDashboard } from './dashboard/dashboard.page'
