export { default as EditType } from './admin-edit/edit-type/edit-type.container'
export { default as EditTile } from './admin-edit/edit-tile/edit-tile.container'
export { default as AddType } from './admin-add/add-type/add-type.page'
export { default as AddTile } from './admin-add/add-tile/add-tile.page'
export { default as AdminMain } from './admin-main/admin-main.page'
export { default as MainTile } from './admin-main/main-tile.page'
export { default as MainType } from './admin-main/main-type.page'