export { default as Login } from './authorization/login'
export { default as Logout } from './authorization/logout'
export { default as EditType } from './edit/edit-type/edit-type.page'
export { default as EditTile } from './edit/edit-tile/edit-tile.page'
export { default as AddType } from './add/add-type/add-type.page'
export { default as AddTile } from './add/add-tile/add-tile.page'
export { default as Dashboard } from './dashboard/dashboard.page'
