export { default as Icon } from './icon/icon.component'
export { default as AsideNavigation } from './aside-navigation/aside-navigation.component'
export { default as TileItem } from './tile-item/tile-item.component'
export { default as TilesList } from './tiles-list/tiles-list.component'
export { default as TypesList } from './types-list/types-list.component'