export { default as FrontPage } from './front/front.page'
export { default as CataloguePage } from './catalogue/catalogue.page'
export { default as OrderPage } from './order/order.page'
export { default as AboutPage } from './about/about.page'
export { default as LocationPage } from './location/location.page'
export { default as ErrorPage } from './error/error.page'