export { default as Front } from './front'
export { default as Catalogue } from './catalogue'
export { default as Product } from './product'
export { default as Order } from './order'
export { default as About } from './about'
export { default as Location } from './location'
export { default as Error } from './error'